'use client';

import { useState, useEffect } from 'react';
import { FaShieldAlt, FaKey, FaCalculator, FaCopy, FaCheck } from 'react-icons/fa';
import { getActiveServerSeedHash, getClientSeed, getNonce, getPreviousRoundInfo, calculateSha256 } from '@/lib/provablyFair';
import styles from './VerificationPanel.module.css';

export default function VerificationPanel({ gameType }) {
  const [activeTab, setActiveTab] = useState('active'); // 'active' | 'verify'
  const [clientSeed, setClientSeedState] = useState('');
  const [serverHash, setServerHash] = useState('');
  const [nonce, setNonce] = useState(0);
  const [prevRound, setPrevRound] = useState(null);
  
  // Custom calculator state
  const [calcServerSeed, setCalcServerSeed] = useState('');
  const [calcClientSeed, setCalcClientSeed] = useState('');
  const [calcNonce, setCalcNonce] = useState('0');
  const [calcResultHash, setCalcResultHash] = useState('');
  const [calculated, setCalculated] = useState(false);

  const [copiedKey, setCopiedKey] = useState(null);

  // Sync state helper
  const syncPanelData = () => {
    setClientSeedState(getClientSeed());
    setServerHash(getActiveServerSeedHash(gameType));
    setNonce(getNonce(gameType));
    
    const prev = getPreviousRoundInfo(gameType);
    setPrevRound(prev);
    if (prev && !calcServerSeed) {
      setCalcServerSeed(prev.serverSeed || '');
      setCalcClientSeed(prev.clientSeed || '');
      setCalcNonce((prev.nonce || 0).toString());
    }
  };

  useEffect(() => {
    syncPanelData();

    // Event listener for vip settings updates
    window.addEventListener('vip-settings-update', syncPanelData);
    return () => window.removeEventListener('vip-settings-update', syncPanelData);
  }, [gameType]);

  const handleCopy = (text, key) => {
    if (typeof window !== 'undefined') {
      navigator.clipboard.writeText(text);
      setCopiedKey(key);
      setTimeout(() => setCopiedKey(null), 1500);
    }
  };

  const handleCalculate = async () => {
    const combo = `${calcServerSeed}-${calcClientSeed}-${calcNonce}`;
    const hash = await calculateSha256(combo);
    setCalcResultHash(hash);
    setCalculated(true);
  };

  const handleUsePrev = () => {
    if (prevRound) {
      setCalcServerSeed(prevRound.serverSeed || '');
      setCalcClientSeed(prevRound.clientSeed || '');
      setCalcNonce((prevRound.nonce || 0).toString());
      setCalculated(false);
      setCalcResultHash('');
    }
  };

  return (
    <div className={styles.verificationCard}>
      {/* Tab Navigation */}
      <div className={styles.tabs}>
        <button
          className={`${styles.tabBtn} ${activeTab === 'active' ? styles.tabActive : ''}`}
          onClick={() => setActiveTab('active')}
        >
          <FaShieldAlt style={{ marginRight: '6px' }} /> Active Round Seeds
        </button>
        <button
          className={`${styles.tabBtn} ${activeTab === 'verify' ? styles.tabActive : ''}`}
          onClick={() => setActiveTab('verify')}
        >
          <FaCalculator style={{ marginRight: '6px' }} /> Provably Fair Audit
        </button>
      </div>

      <div className={styles.tabContent}>
        {/* ACTIVE SEEDS TAB */}
        {activeTab === 'active' && (
          <div className={styles.activeSeedsGrid}>
            <div className={styles.infoRow}>
              <div className={styles.infoMeta}>
                <span className={styles.label}>Server Seed Hash (SHA-256)</span>
                <span className={styles.desc}>The encrypted server seed committed to this round.</span>
              </div>
              <div className={styles.valueContainer}>
                <div className={styles.valueText}>{serverHash}</div>
                <button className={styles.copyBtn} onClick={() => handleCopy(serverHash, 'active_hash')}>
                  {copiedKey === 'active_hash' ? <span className={styles.copyCheck}>✓</span> : <span className={styles.copyIcon}>❐</span>}
                </button>
              </div>
            </div>

            <div className={styles.infoRow}>
              <div className={styles.infoMeta}>
                <span className={styles.label}>Client Seed</span>
                <span className={styles.desc}>Custom seed generated by your browser (edit in VIP panel).</span>
              </div>
              <div className={styles.valueContainer}>
                <div className={styles.valueText}>{clientSeed}</div>
                <button className={styles.copyBtn} onClick={() => handleCopy(clientSeed, 'active_client')}>
                  {copiedKey === 'active_client' ? <span className={styles.copyCheck}>✓</span> : <span className={styles.copyIcon}>❐</span>}
                </button>
              </div>
            </div>

            <div className={styles.infoRow}>
              <div className={styles.infoMeta}>
                <span className={styles.label}>Nonce</span>
                <span className={styles.desc}>Incrementing counter of rounds played on this server seed.</span>
              </div>
              <div className={styles.valueContainer}>
                <div className={styles.valueText} style={{ fontFamily: 'Orbitron, monospace', fontWeight: 600 }}>{nonce}</div>
                <button className={styles.copyBtn} onClick={() => handleCopy(nonce.toString(), 'active_nonce')}>
                  {copiedKey === 'active_nonce' ? <span className={styles.copyCheck}>✓</span> : <span className={styles.copyIcon}>❐</span>}
                </button>
              </div>
            </div>
          </div>
        )}

        {/* VERIFY TAB (AUDITING CALCULATOR) */}
        {activeTab === 'verify' && (
          <div className={styles.verifyTab}>
            {prevRound ? (
              <div className={styles.prevBanner}>
                <p>
                  <strong>Last Round Finished:</strong> Nonce {prevRound.nonce} (Result: {prevRound.outcomeDesc})
                </p>
                <button className={styles.usePrevBtn} onClick={handleUsePrev}>
                  Load Previous Round Data
                </button>
              </div>
            ) : (
              <p className={styles.noPrevText}>No rounds completed yet. Play a round to unlock auditing details.</p>
            )}

            <div className={styles.calculatorGrid}>
              <div className={styles.inputGroup}>
                <label className={styles.inputLabel}>Server Seed (Unhashed)</label>
                <input
                  type="text"
                  className={styles.input}
                  value={calcServerSeed}
                  onChange={(e) => { setCalcServerSeed(e.target.value); setCalculated(false); }}
                  placeholder="Unhashed Server Hex Seed"
                />
              </div>

              <div className={styles.inputGroup}>
                <label className={styles.inputLabel}>Client Seed</label>
                <input
                  type="text"
                  className={styles.input}
                  value={calcClientSeed}
                  onChange={(e) => { setCalcClientSeed(e.target.value); setCalculated(false); }}
                  placeholder="Client Seed"
                />
              </div>

              <div className={styles.inputGroup}>
                <label className={styles.inputLabel}>Nonce</label>
                <input
                  type="number"
                  className={styles.input}
                  value={calcNonce}
                  onChange={(e) => { setCalcNonce(e.target.value); setCalculated(false); }}
                  placeholder="0"
                />
              </div>

              <button className={styles.calculateBtn} onClick={handleCalculate}>
                Calculate Outcome Hash
              </button>

              {calculated && (
                <div className={styles.calcResult}>
                  <div className={styles.calcRow}>
                    <span className={styles.calcLabel}>Calculated SHA-256 Hash:</span>
                    <div className={styles.calcHashRow}>
                      <span className={styles.hashOutput}>{calcResultHash}</span>
                      <button className={styles.copyBtn} onClick={() => handleCopy(calcResultHash, 'calc_hash')}>
                        {copiedKey === 'calc_hash' ? <span className={styles.copyCheck}>✓</span> : <span className={styles.copyIcon}>❐</span>}
                      </button>
                    </div>
                  </div>
                  {prevRound && calcResultHash === prevRound.resultHash && (
                    <div className={styles.verifySuccess}>
                      ✓ SUCCESS: Outcome hash matches the completed round hash! Provably fair status verified.
                    </div>
                  )}
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
